# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UniversalPackages@0
  displayName: 'Universal download'
  inputs:
    vstsFeed: 'a06735a4-cf5f-4dfc-9e88-22372c251ffd/b6c40c50-0baf-4700-9c24-ea2deecb3512'
    vstsFeedPackage: '8537e821-dc54-4a8c-8f7b-2d6f08e4bbac'
    vstsPackageVersion: 0.0.1


- task: AzureFunctionApp@1
  displayName: 'Azure Function App Deploy: testfuncappp'
  inputs:
    azureSubscription: 'Pay-As-You-Go (40783f5c-2558-41a9-a5af-97b47669376e)'
    appType: functionAppLinux
    appName: testfuncappp
    package: '$(System.DefaultWorkingDirectory)/291.zip'
