steps:

- bash: |
   if [ -f extensions.csproj ]
   then
       dotnet build extensions.csproj --output ./bin
   fi
  displayName: 'Build extensions'


- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: 3.6

- bash: |
   python3.6 -m venv worker_venv
   source worker_venv/bin/activate
   pip3.6 install setuptools
   pip3.6 install -r ./requirements.txt
  displayName: 'Install Application Dependencies'


- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false


- task: UniversalPackages@0
  displayName: 'Universal publish'
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    vstsFeedPublish: 'a06735a4-cf5f-4dfc-9e88-22372c251ffd/b6c40c50-0baf-4700-9c24-ea2deecb3512'
    vstsFeedPackagePublish: pythonv1.2

- task: UniversalPackages@0
  displayName: 'Universal download'
  inputs:
    vstsFeed: 'a06735a4-cf5f-4dfc-9e88-22372c251ffd/b6c40c50-0baf-4700-9c24-ea2deecb3512'
    vstsFeedPackage: '8537e821-dc54-4a8c-8f7b-2d6f08e4bbac'
    vstsPackageVersion: 0.0.1


- task: AzureFunctionApp@1
  displayName: 'Azure Function App Deploy: testfuncappp'
  inputs:
    azureSubscription: 'Pay-As-You-Go (40783f5c-2558-41a9-a5af-97b47669376e)'
    appType: functionAppLinux
    appName: testfuncappp
    package: '$(System.DefaultWorkingDirectory)/291.zip'