# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- template: variables.yml
steps:
- task: UniversalPackages@0
  displayName: 'Universal download'
  inputs:
    vstsFeed: '$(var_vstsFeed)'
    vstsFeedPackage: '$(var_vstsFeedPackage)'
    vstsPackageVersion: '$(var_vstsPackageVersion)'


- task: AzureFunctionApp@1
  displayName: 'Azure Function App Deploy: testfuncappp'
  inputs:
    azureSubscription: '$(var_service_connection)'
    appType: functionAppLinux
    appName: $(var_appname)
    package: '$(System.DefaultWorkingDirectory)//*.zip'
